server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 8084
spring:
  profiles: prod   #指定属于哪个环境
#person:
#  lastName: hello
#  age: 18
#  boss: false
#  birth: 2020/04/09
#  maps: {k1: v1,k2: l2}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 12